import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProviderWrapper } from '@/components/theme-provider-wrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'MicroApp',
  description: 'Generated by create next app',
};

// Viewport configuration for mobile-responsive design
// Disables pinch-to-zoom and ensures proper mobile rendering
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
      </body>
    </html>
  );
}
